apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "restic-volume-populator.fullname" . }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - persistentvolumeclaims
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources:
      - persistentvolumes
    verbs: ["get", "watch", "list", "patch"]

  - apiGroups: [""]
    resources:
      - pods/log
    verbs: ["get", "watch", "list"]
  - apiGroups: ["events.k8s.io"]
    resources:
      - events
    verbs: ["create"]

  - apiGroups: ["customresourcedefinitions.apiextensions.k8s.io"]
    resources:
      - resticvolumepopulators.ansarhun.github.com
    verbs: ["create", "update"]

  - apiGroups: ["ansarhun.github.com"]
    resources:
      - resticvolumepopulators
    verbs: ["get", "watch", "list", "update"]
  - apiGroups: ["ansarhun.github.com"]
    resources:
      - resticvolumepopulators/status
    verbs: ["update"]
